<a href="https://colab.research.google.com/github/hahahamamama/ResNeStTest/blob/master/JeffTensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
print(tf.config.list_physical_devices('GPU'))

[]


In [ ]:
a=tf.constant('Hello,Deep Learning.')

In [ ]:
a

<tf.Tensor: shape=(), dtype=string, numpy=b'Hello,Deep Learning.'>

In [ ]:
tf.strings.lower(a)

<tf.Tensor: shape=(), dtype=string, numpy=b'hello,deep learning.'>

In [ ]:
a

<tf.Tensor: shape=(), dtype=string, numpy=b'Hello,Deep Learning.'>

In [ ]:
a=tf.constant(True)

In [ ]:
a

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
a=tf.constant([True,False])

In [ ]:
a

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([ True, False])>

In [ ]:
a=tf.constant(True)

In [ ]:
a is True

False

In [ ]:
a==True

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
import numpy as np

In [ ]:
np.pi

3.141592653589793

In [ ]:
tf.constant(np.pi,dtype=tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=3.1415927>

In [ ]:
tf.constant(np.pi,dtype=tf.float64)

<tf.Tensor: shape=(), dtype=float64, numpy=3.141592653589793>

In [ ]:
a.dtype

tf.bool

In [ ]:
print('before:',a.dtype)

before: <dtype: 'bool'>


In [ ]:
a=tf.constant(np.pi,dtype=tf.float16)

In [ ]:
tf.cast(a,tf.double)

<tf.Tensor: shape=(), dtype=float64, numpy=3.140625>

In [ ]:
a=tf.constant([-1,0,1,2])

In [ ]:
tf.cast(a,tf.bool)

<tf.Tensor: shape=(4,), dtype=bool, numpy=array([ True, False,  True,  True])>

In [ ]:
a=tf.constant([-1,0,1,2])

In [ ]:
aa=tf.Variable(a)

In [ ]:
aa.name

'Variable:0'

In [ ]:
aa.trainable

True

In [ ]:
a=tf.Variable([[1,2],[3,4]])

In [ ]:
a

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
tf.convert_to_tensor([1,2.])

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [ ]:
tf.convert_to_tensor(np.array([[1,2.],[3,4]]))

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1., 2.],
       [3., 4.]])>

In [ ]:
tf.zeros([]),tf.ones([])

(<tf.Tensor: shape=(), dtype=float32, numpy=0.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.0>)

In [ ]:
tf.zeros([5])

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([0., 0., 0., 0., 0.], dtype=float32)>

In [ ]:
tf.zeros([2,2])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [ ]:
a=tf.ones([2,3])

In [ ]:
tf.zeros_like(a)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [ ]:
tf.zeros(a.shape)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [ ]:
tf.fill([10,10],99.)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[99., 99., 99., 99., 99., 99., 99., 99., 99., 99.],
       [99., 99., 99., 99., 99., 99., 99., 99., 99., 99.],
       [99., 99., 99., 99., 99., 99., 99., 99., 99., 99.],
       [99., 99., 99., 99., 99., 99., 99., 99., 99., 99.],
       [99., 99., 99., 99., 99., 99., 99., 99., 99., 99.],
       [99., 99., 99., 99., 99., 99., 99., 99., 99., 99.],
       [99., 99., 99., 99., 99., 99., 99., 99., 99., 99.],
       [99., 99., 99., 99., 99., 99., 99., 99., 99., 99.],
       [99., 99., 99., 99., 99., 99., 99., 99., 99., 99.],
       [99., 99., 99., 99., 99., 99., 99., 99., 99., 99.]], dtype=float32)>

In [ ]:
tf.random.normal([5,5],4,5)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[12.209058  , 13.39993   ,  1.511828  ,  5.1853247 , -4.47993   ],
       [ 0.92288303,  3.6808705 ,  7.6875076 , 10.908468  ,  4.3917384 ],
       [ 4.5938835 ,  7.1148834 ,  8.517881  ,  6.3242636 , 12.55228   ],
       [ 9.378788  ,  3.9415398 ,  2.9553533 ,  6.0703697 ,  0.46198297],
       [ 1.9936523 ,  3.677814  ,  5.119338  ,  3.6249146 ,  0.36580658]],
      dtype=float32)>

In [ ]:
tf.random.normal([5,5],mean=4,stddev=5)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[21.530258  ,  1.083662  , -0.9634986 ,  6.4824343 , -0.38508558],
       [ 7.6364245 ,  6.1953783 , -4.884907  ,  4.8506784 ,  1.306421  ],
       [ 6.4899454 , 11.5451975 ,  1.5576665 ,  0.47049308,  4.1038446 ],
       [-7.3916626 , 14.332233  ,  1.1519961 ,  7.7658854 , 10.933249  ],
       [ 0.07445288,  3.1696649 ,  0.82124734, 16.63048   ,  2.5521016 ]],
      dtype=float32)>

In [ ]:
tf.random.uniform([2,2],10,100)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[66.20279 , 53.450607],
       [20.386501, 73.981995]], dtype=float32)>

In [ ]:
tf.random.uniform([2,2],10,maxval=100,dtype=tf.int32)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[26, 66],
       [47, 23]], dtype=int32)>

In [ ]:
tf.range(-10,2,1)

<tf.Tensor: shape=(12,), dtype=int32, numpy=
array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1],
      dtype=int32)>

In [ ]:
out=tf.random.uniform([4,10])

In [ ]:
y=tf.constant([2,3,2,0])

In [ ]:
y=tf.one_hot(y,depth=10)

In [ ]:
loss=tf.keras.losses.mse(y,out)

In [ ]:
loss=tf.reduce_mean(loss)

In [ ]:
print(loss)

tf.Tensor(0.36068684, shape=(), dtype=float32)


In [ ]:
import keras

In [ ]:
fc=keras.layers.Dense(3)

In [ ]:
fc.build(input_shape=(2,4))

In [ ]:
fc.bias

<tf.Variable 'bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>

In [ ]:
x=tf.random.normal([2,4])

In [ ]:
x

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[-0.37886983,  0.959436  , -0.05064312,  0.27409002],
       [ 0.27027926,  0.22748879,  1.2880307 , -0.8966711 ]],
      dtype=float32)>

In [ ]:
w=tf.ones([4,3])

In [ ]:
b=tf.zeros([3])

In [ ]:
o=x@w+b

In [ ]:
o

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.804013  , 0.804013  , 0.804013  ],
       [0.88912773, 0.88912773, 0.88912773]], dtype=float32)>

In [ ]:
fc=keras.layers.Dense(3)

In [ ]:
fc.build(input_shape=(2,4))

In [ ]:
fc.kernel

<tf.Variable 'kernel:0' shape=(4, 3) dtype=float32, numpy=
array([[ 0.2147429 , -0.4344064 ,  0.71342754],
       [ 0.7461636 ,  0.64161575, -0.29920298],
       [-0.62198573,  0.04573381,  0.901494  ],
       [-0.11728305, -0.59829116,  0.8688239 ]], dtype=float32)>

In [ ]:
(x_train,y_train),(x_test,y_test)=keras.datasets.imdb.load_data(num_words=10000)

17465344/17464789 [==============================] - 0s 0us/step


<string>:6: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/datasets/imdb.py:159: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  x_train, y_train = np.array(xs[:idx]), np.array(labels[:idx])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/datasets/imdb.py:160: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 

In [ ]:
x_train=keras.preprocessing.sequence.pad_sequences(x_train,maxlen=80)

In [ ]:
x_train

array([[  15,  256,    4, ...,   19,  178,   32],
       [ 125,   68,    2, ...,   16,  145,   95],
       [ 645,  662,    8, ...,    7,  129,  113],
       ...,
       [ 529,  443,    2, ...,    4, 3586,    2],
       [ 286, 1814,   23, ...,   12,    9,   23],
       [  97,   90,   35, ...,  204,  131,    9]], dtype=int32)

In [ ]:
embedding=keras.layers.Embedding(10000,100)

In [ ]:
embedding

In [ ]:
out=embedding(x_train)

In [ ]:
out

<tf.Tensor: shape=(25000, 80, 100), dtype=float32, numpy=
array([[[-0.04021563,  0.01307968, -0.04984891, ...,  0.04220096,
         -0.00344938, -0.00430394],
        [-0.04188459, -0.03336221, -0.00560045, ..., -0.03291296,
          0.04028597, -0.04623732],
        [-0.01317321,  0.01222872,  0.0363437 , ..., -0.02420864,
          0.04716537, -0.0266579 ],
        ...,
        [-0.04043851,  0.00680863, -0.0030802 , ...,  0.02932615,
         -0.02425534, -0.03516083],
        [-0.00592532, -0.00583968, -0.04690992, ..., -0.0398738 ,
          0.0185179 , -0.02911673],
        [ 0.03481025,  0.04163137, -0.04750731, ..., -0.00856458,
         -0.026806  , -0.00657086]],

       [[-0.01392273,  0.03192449, -0.0387852 , ...,  0.0127793 ,
          0.02118481, -0.04661726],
        [-0.00458124,  0.00795797,  0.01611234, ..., -0.03099334,
          0.03805638, -0.02571954],
        [ 0.03667558,  0.02020805,  0.01759786, ..., -0.03963963,
          0.03157851,  0.01505372],
        .

In [ ]:
out.shape

TensorShape([25000, 80, 100])

In [ ]:
x=tf.random.normal([4,32,32,3])

In [ ]:
layer=keras.layers.Conv2D(16,kernel_size=3)

In [ ]:
out=layer(x)

In [ ]:
out.shape

TensorShape([4, 30, 30, 16])

In [ ]:
out

<tf.Tensor: shape=(4, 30, 30, 16), dtype=float32, numpy=
array([[[[ 6.41736209e-01,  4.31328177e-01,  8.37394893e-02, ...,
          -2.52457768e-01, -3.19739543e-02, -7.06923977e-02],
         [ 2.41924748e-01, -2.42845073e-01,  2.60963231e-01, ...,
           8.69800270e-01, -2.84981411e-02, -2.61779547e-01],
         [-3.13759446e-01,  9.80254591e-01, -2.54607260e-01, ...,
           1.54775992e-01,  4.07788865e-02,  3.14680070e-01],
         ...,
         [-3.96215230e-01,  4.41411436e-01,  4.43613112e-01, ...,
           6.86065927e-02,  4.49731082e-01,  7.98755139e-02],
         [-5.99994302e-01, -6.42619371e-01, -5.50456583e-01, ...,
          -5.18553972e-01,  2.84141712e-02, -1.18125808e+00],
         [ 7.15644479e-01,  5.49348414e-01,  2.95093030e-01, ...,
          -1.45463571e-01, -3.08005929e-01, -4.35372353e-01]],

        [[ 4.21181560e-01, -9.11426306e-01,  4.93799239e-01, ...,
          -2.53365785e-01, -4.24380630e-01, -1.74045098e+00],
         [-6.84431612e-01,  1.1

In [ ]:
layer.kernel.shape

TensorShape([3, 3, 3, 16])

In [ ]:
layer.kernel

<tf.Variable 'conv2d/kernel:0' shape=(3, 3, 3, 16) dtype=float32, numpy=
array([[[[-0.00177465, -0.13930126, -0.07007159, -0.13333134,
           0.04572973, -0.09484395,  0.00676472, -0.14954758,
           0.09313449,  0.07274753,  0.07477996,  0.16393512,
          -0.18625444, -0.05293265,  0.11305374, -0.18046236],
         [ 0.13383609, -0.10349318,  0.1678178 , -0.05469649,
          -0.04691553, -0.15728866, -0.10692824, -0.17447257,
           0.15385208, -0.02705532, -0.06401317, -0.01020403,
          -0.01031335,  0.1344577 ,  0.17390084,  0.12384853],
         [ 0.15981814, -0.03448802, -0.11534458, -0.05874209,
           0.05472408, -0.18065307,  0.12119329, -0.04338874,
          -0.02705956,  0.14774185, -0.03651974,  0.13808504,
          -0.07881975,  0.01450182,  0.03709339, -0.03032461]],

        [[-0.17916079,  0.14753613,  0.01486915, -0.0247695 ,
          -0.13240515, -0.1602776 ,  0.02637056,  0.02843352,
           0.00643589, -0.12098257, -0.12191735,  0.05

In [ ]:
x=tf.random.normal([4,32,32,3])

In [ ]:
x[0]

<tf.Tensor: shape=(32, 32, 3), dtype=float32, numpy=
array([[[-6.91091001e-01, -9.55639899e-01,  1.34626305e+00],
        [ 5.49653172e-01, -1.23678839e+00,  3.09736371e-01],
        [-2.04623628e+00, -1.03649068e+00,  1.06056166e+00],
        ...,
        [ 2.11782479e+00,  2.79717743e-01,  1.24170613e+00],
        [ 8.21008503e-01, -3.00894976e-01,  1.79042494e+00],
        [ 5.33068478e-01, -8.48693490e-01,  5.73100030e-01]],

       [[-3.02203864e-01,  2.46595597e+00,  5.30515432e-01],
        [-1.06867337e+00, -9.69091117e-01,  1.13511658e+00],
        [ 1.35328388e+00,  2.21436396e-02, -6.57513678e-01],
        ...,
        [-5.00416219e-01,  3.37892115e-01,  5.21633625e-01],
        [ 2.52599269e-01, -1.63074613e+00, -2.66508281e-01],
        [ 4.17596102e-01, -5.76509953e-01, -1.36518523e-01]],

       [[-5.33104062e-01, -5.39849222e-01, -9.26008046e-01],
        [-1.21050155e+00,  6.90985203e-01, -1.14434466e-01],
        [ 6.46059453e-01,  5.78921080e-01, -1.93042588e+00],
  

In [ ]:
x[1,9,2]

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.142375  , 0.34132123, 0.5243169 ], dtype=float32)>

In [ ]:
x[:,:,:,1]

<tf.Tensor: shape=(4, 32, 32), dtype=float32, numpy=
array([[[-9.55639899e-01, -1.23678839e+00, -1.03649068e+00, ...,
          2.79717743e-01, -3.00894976e-01, -8.48693490e-01],
        [ 2.46595597e+00, -9.69091117e-01,  2.21436396e-02, ...,
          3.37892115e-01, -1.63074613e+00, -5.76509953e-01],
        [-5.39849222e-01,  6.90985203e-01,  5.78921080e-01, ...,
          2.57410049e-01, -8.88333678e-01, -4.12453234e-01],
        ...,
        [ 6.05799437e-01, -5.63047051e-01,  4.68540527e-02, ...,
         -1.87677312e+00,  9.06657279e-01, -3.57351899e-02],
        [-1.16456902e+00, -7.47061253e-01,  9.48083043e-01, ...,
         -6.59754992e-01,  2.74642277e+00,  1.02190554e-01],
        [-9.39059794e-01,  9.43146288e-01,  1.41898561e+00, ...,
          3.58155936e-01,  2.48798156e+00, -2.48224184e-01]],

       [[ 5.93706906e-01,  8.20388734e-01, -1.21948290e+00, ...,
          6.12778068e-02,  1.24495745e+00, -1.16876626e+00],
        [ 1.54604363e+00,  9.15497005e-01, -2.2519

In [ ]:
x[0,::-2,::-1]

<tf.Tensor: shape=(16, 32, 3), dtype=float32, numpy=
array([[[ 0.88666755, -0.24822418, -1.2538247 ],
        [ 0.30341682,  2.4879816 , -1.6379129 ],
        [ 0.15887192,  0.35815594,  1.080728  ],
        ...,
        [-0.8130839 ,  1.4189856 , -0.7749167 ],
        [-0.56970537,  0.9431463 , -1.0806775 ],
        [-1.3938258 , -0.9390598 , -1.0641809 ]],

       [[ 0.17133339, -0.03573519,  0.11917914],
        [-0.88529646,  0.9066573 ,  0.4041207 ],
        [-0.43430576, -1.8767731 , -0.13841969],
        ...,
        [ 0.93149656,  0.04685405,  1.2505509 ],
        [ 1.3647121 , -0.56304705,  0.08353273],
        [ 0.93028545,  0.60579944,  0.11957561]],

       [[-2.3796139 ,  0.10937788, -1.1170167 ],
        [-0.13986047,  0.3271085 , -1.4719396 ],
        [ 1.1422403 ,  0.86309844, -0.9397983 ],
        ...,
        [-0.7965998 , -0.8594849 ,  0.13006984],
        [ 0.57853484, -0.63068634,  0.96562636],
        [-0.7060746 ,  0.706864  ,  0.79350907]],

       ...,

       

In [ ]:
x[2:3,...,1:2]

<tf.Tensor: shape=(1, 32, 32, 1), dtype=float32, numpy=
array([[[[-0.30817637],
         [ 0.01482868],
         [ 0.79846716],
         ...,
         [ 0.41847888],
         [ 0.4757134 ],
         [ 1.9200722 ]],

        [[-0.6832474 ],
         [-0.5574503 ],
         [-1.8008888 ],
         ...,
         [-0.77571654],
         [ 0.9953423 ],
         [ 0.48140794]],

        [[-0.23892935],
         [ 0.61641866],
         [-0.02349695],
         ...,
         [ 0.88957053],
         [-2.1597252 ],
         [-0.07508049]],

        ...,

        [[ 1.8475822 ],
         [ 0.14727978],
         [-0.11954557],
         ...,
         [ 1.2076447 ],
         [ 0.35917285],
         [ 0.55293787]],

        [[ 0.59564793],
         [-0.18813346],
         [ 1.8282852 ],
         ...,
         [ 0.61504567],
         [ 1.716924  ],
         [ 0.2455574 ]],

        [[ 0.254902  ],
         [ 0.86086476],
         [ 2.1999195 ],
         ...,
         [-0.59962535],
         [ 1.4533061

In [ ]:
x=tf.range(96)

In [ ]:
x=tf.reshape(x,[2,4,4,3])

In [ ]:
x

<tf.Tensor: shape=(2, 4, 4, 3), dtype=int32, numpy=
array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17],
         [18, 19, 20],
         [21, 22, 23]],

        [[24, 25, 26],
         [27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44],
         [45, 46, 47]]],


       [[[48, 49, 50],
         [51, 52, 53],
         [54, 55, 56],
         [57, 58, 59]],

        [[60, 61, 62],
         [63, 64, 65],
         [66, 67, 68],
         [69, 70, 71]],

        [[72, 73, 74],
         [75, 76, 77],
         [78, 79, 80],
         [81, 82, 83]],

        [[84, 85, 86],
         [87, 88, 89],
         [90, 91, 92],
         [93, 94, 95]]]], dtype=int32)>

In [ ]:
x.ndim,x.shape

(4, TensorShape([2, 4, 4, 3]))

In [ ]:
tf.reshape(x,[2,-1])

<tf.Tensor: shape=(2, 48), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
        64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
        80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95]],
      dtype=int32)>

In [ ]:
tf.reshape(x,[2,4,-1])

<tf.Tensor: shape=(2, 4, 12), dtype=int32, numpy=
array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47]],

       [[48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71],
        [72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83],
        [84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95]]], dtype=int32)>

In [ ]:
tf.reshape(x,[2,-1,3])

<tf.Tensor: shape=(2, 16, 3), dtype=int32, numpy=
array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35],
        [36, 37, 38],
        [39, 40, 41],
        [42, 43, 44],
        [45, 46, 47]],

       [[48, 49, 50],
        [51, 52, 53],
        [54, 55, 56],
        [57, 58, 59],
        [60, 61, 62],
        [63, 64, 65],
        [66, 67, 68],
        [69, 70, 71],
        [72, 73, 74],
        [75, 76, 77],
        [78, 79, 80],
        [81, 82, 83],
        [84, 85, 86],
        [87, 88, 89],
        [90, 91, 92],
        [93, 94, 95]]], dtype=int32)>

In [ ]:
x=tf.random.uniform([28,28],maxval=10,dtype=tf.int32)

In [ ]:
x

<tf.Tensor: shape=(28, 28), dtype=int32, numpy=
array([[4, 2, 6, 9, 5, 3, 0, 7, 8, 8, 6, 2, 0, 3, 5, 7, 0, 0, 9, 5, 3, 6,
        2, 8, 7, 8, 0, 6],
       [8, 4, 8, 4, 3, 4, 5, 7, 7, 8, 0, 4, 6, 9, 9, 0, 1, 4, 2, 8, 0, 9,
        4, 6, 3, 9, 6, 6],
       [0, 4, 0, 7, 6, 5, 0, 9, 0, 9, 4, 9, 5, 7, 0, 5, 8, 1, 6, 6, 8, 7,
        0, 6, 8, 8, 8, 1],
       [0, 0, 9, 0, 8, 2, 1, 1, 4, 0, 7, 3, 1, 0, 1, 3, 0, 5, 3, 9, 4, 8,
        2, 4, 1, 6, 4, 1],
       [4, 7, 6, 0, 1, 5, 0, 1, 1, 8, 4, 3, 3, 4, 5, 0, 1, 1, 4, 5, 5, 5,
        6, 0, 1, 9, 0, 3],
       [7, 4, 2, 8, 7, 4, 3, 9, 7, 9, 1, 0, 7, 9, 9, 6, 8, 0, 2, 0, 4, 6,
        0, 6, 4, 8, 8, 4],
       [3, 3, 1, 5, 9, 3, 2, 8, 4, 1, 0, 5, 9, 0, 8, 5, 3, 3, 9, 1, 5, 1,
        1, 6, 2, 5, 7, 3],
       [7, 5, 2, 2, 6, 9, 0, 4, 8, 2, 3, 1, 1, 0, 7, 3, 9, 6, 0, 7, 1, 6,
        7, 2, 9, 8, 3, 7],
       [9, 0, 6, 9, 6, 1, 8, 4, 5, 9, 9, 0, 2, 4, 8, 1, 5, 3, 6, 6, 1, 1,
        7, 5, 9, 7, 8, 6],
       [6, 0, 7, 4, 2, 5, 8, 0, 3, 8, 4, 0,

In [ ]:
x=tf.expand_dims(x,axis=1)

In [ ]:
print(x.shape)

(28, 28)


In [ ]:
x=tf.squeeze(x,axis=-1)

In [ ]:
x=tf.random.normal([2,32,32,3])

In [ ]:
tf.transpose(x,perm=[0,3,1,2])

<tf.Tensor: shape=(2, 3, 32, 32), dtype=float32, numpy=
array([[[[-1.7072102 , -1.5876163 , -1.6316879 , ...,  0.91721195,
          -3.5484471 ,  0.61443174],
         [ 0.16777705, -2.2776563 , -1.7677872 , ...,  0.8422285 ,
          -0.3439279 , -1.805317  ],
         [ 0.03265829, -1.9781032 , -0.93792564, ...,  0.44051397,
          -0.62722963,  1.0293959 ],
         ...,
         [ 0.35546738,  0.26608878, -0.62770677, ...,  1.6401595 ,
           0.93484765, -1.089647  ],
         [-1.0111406 , -1.3078455 , -1.8999684 , ..., -0.2845574 ,
           0.52947295,  1.3535995 ],
         [ 1.7796613 ,  0.04756573, -1.6399602 , ...,  0.9284565 ,
          -0.6998331 ,  2.0662105 ]],

        [[ 0.99437696, -2.0617273 , -1.3504783 , ..., -0.41868478,
           0.05891861, -0.45127887],
         [-1.0253081 ,  1.1962854 , -1.5994718 , ..., -0.47898218,
           0.45689481, -0.24723117],
         [ 0.10302072, -1.7915843 ,  0.23674344, ..., -0.18196276,
           0.29916683, -1.678

In [ ]:
b=tf.constant([1,2])


In [ ]:
b

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [ ]:
b=tf.expand_dims(b,axis=0)

In [ ]:
b

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[1, 2]], dtype=int32)>

In [ ]:
b=tf.tile(b,multiples=[2,1])

In [ ]:
b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [1, 2]], dtype=int32)>

In [ ]:
a=tf.random.normal([2,32,32,1])

In [ ]:
b=tf.random.normal([32,32])

In [ ]:
a+b,a-b,a*b,a/b

(<tf.Tensor: shape=(2, 32, 32, 32), dtype=float32, numpy=
 array([[[[ 1.0831228 ,  0.2898424 ,  0.7922208 , ...,  1.5157006 ,
           -1.5810535 , -0.3242902 ],
          [ 0.12577415, -3.5538416 , -2.3348489 , ..., -2.5630035 ,
           -3.1643782 , -3.139038  ],
          [ 0.4031158 ,  1.2440271 , -0.97776055, ...,  1.6443034 ,
            0.09042352, -1.853929  ],
          ...,
          [-0.83983856,  0.58857834, -0.98153776, ...,  0.8090176 ,
           -0.5841274 ,  0.8814333 ],
          [ 2.581013  ,  2.5590954 ,  2.0376956 , ...,  1.6205969 ,
            1.6333058 ,  1.7841972 ],
          [ 1.4167433 , -1.3915906 , -0.11460641, ..., -0.17803106,
            0.3256532 , -0.6799959 ]],
 
         [[ 1.4776047 ,  0.6843243 ,  1.1867027 , ...,  1.9101825 ,
           -1.1865716 ,  0.07019174],
          [ 2.8637094 , -0.81590617,  0.4030864 , ...,  0.17493166,
           -0.42644283, -0.40110275],
          [ 2.1839807 ,  3.0248919 ,  0.80310434, ...,  3.4251683 ,
        

In [ ]:
x=tf.constant([1.,2.])

In [ ]:
x=10**x

In [ ]:
x

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 10., 100.], dtype=float32)>

In [ ]:
tf.math.log(x)/tf.math.log(10.)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [ ]:
a=tf.random.normal([4,28,32])

In [ ]:
b=tf.random.normal([32,16])

In [ ]:
a@b

<tf.Tensor: shape=(4, 28, 16), dtype=float32, numpy=
array([[[ 2.76474667e+00,  2.84854102e+00, -6.46325159e+00, ...,
         -1.01410234e+00,  1.15293512e+01, -6.00480318e-01],
        [-8.19037724e+00, -3.96122694e+00, -2.56269979e+00, ...,
          1.26320009e+01,  5.18923521e-01,  3.44954109e+00],
        [-3.39838433e+00, -8.17367458e+00, -5.19704771e+00, ...,
          6.10738182e+00, -8.98570728e+00, -4.25290680e+00],
        ...,
        [ 1.34251142e+00,  2.85788107e+00,  4.86293125e+00, ...,
          5.96931791e+00, -2.52008605e+00,  3.44669890e+00],
        [ 5.40652037e+00,  7.93637896e+00, -1.55478692e+00, ...,
          3.96216512e+00, -2.23669887e+00, -2.89004445e+00],
        [-2.14426827e+00, -5.14782572e+00,  1.71076143e+00, ...,
         -5.26773095e-01, -3.57252669e+00, -1.22437453e+00]],

       [[-9.14007282e+00, -4.05790377e+00, -1.49617052e+00, ...,
          7.31887817e+00,  5.22728682e+00,  5.16750669e+00],
        [ 3.40620613e+00,  9.43399048e+00, -5.8278

In [ ]:
w1=tf.Variable(tf.random.truncated_normal([784,256],stddev=0.1))

In [ ]:
b1=tf.Variable(tf.zeros([256]))

In [ ]:
w2=tf.Variable(tf.random.truncated_normal([256,128],stddev=0.1))

In [ ]:
b2=tf.Variable(tf.zeros([128]))

In [ ]:
w3=tf.Variable(tf.zeros([10]))

In [ ]:
x=tf.reshape(x,[-1,28*28])

InvalidArgumentError: ignored